# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ASTRID - Analytic System Tracking Rapid Infant Development
email: crporter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Analyzing FeedBaby data and creating pretty visualizations
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cdnveg
github_username:  canadianveggie
github_url: https://github.com/canadianveggie/astrid
google_analytics: UA-88136017-1

flickr:
  api_key: 29bcddc4ee38d133a1d53cd1e20a0a6a
  user_id: 34962573@N00

sass:
  sass_dir: vendor/bootstrap-sass/stylesheets/

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - bower.json
  - Gruntfile.js
  - bower_components
  - package.json
  - node_modules
